### ISSUE TITLE
How to put modal window in to separate component?

### ISSUE THREAD

**Issue by rendomnet** [mmazzarolo/react-native-animated-modal#1]
I have big problems with this.
Can you make simple example?

**Comment by mmazzarolo** [comment]
Sorry for being late :)
Can you give me a bit more detail on the result you want to achieve? 

Also, did you already take a look at the [example?](https://github.com/mmazzarolo/react-native-animated-modal/blob/master/src/index.js).

**Comment by mmazzarolo** [comment]
I'm closing the issue, feel free to re-open it if needed.
