### ISSUE TITLE
A way to specify no animation

### ISSUE THREAD

**Issue by stonepreston** [mmazzarolo/react-native-animated-modal#2]
is there a way to specify no animation? I would like to be able to have no animation (so it just appears) for showing the modal, and slide out for hiding the modal

**Comment by mmazzarolo** [comment]
Hey @stonepreston, that's a totally legit question.  
I'm thinking about the best way to implement such a feature and there are two options at the moment that may fit:
- Disable a specific animation when its timing is `0` (less declarative, more concise) - right now setting it to `0` will just trigger the default timing 
- Add a prop for each animation specifying if the animations should be enabled or not (more declarative, more verbose)  

In the meanwhile you can set the timing to `1` and it will make the animation disappear (unless your eyes can catch the 1 ms animation :)).

**Comment by stonepreston** [comment]
alright I am going to implement an animated modal in a bit, Ill let you know how it goes

**Comment by mmazzarolo** [comment]
@stonepreston I'm closing this, let me know if it worked for you :)

**Comment by Donhv** [comment]
@mmazzarolo my eyes very very perfect :))
thanks u <3
