### ISSUE TITLE
Modal does not appear

### ISSUE THREAD

**Issue by stonepreston** [mmazzarolo/react-native-animated-modal#3]
I am trying to get a simple modal to appear on screen using RN v0.40.0. I have imported the animated modal using

`import Modal from 'react-native-animated-modal';`

and have inserted a modal component into my view:

```
 <View>
              <Text style={{marginTop: 80}}>Hello</Text>
               
               <Modal
                isVisible={true}
               >
               <Navigator
                initialRoute={{ title: 'SignUp', index: 0 }}
                renderScene={(route, navigator) =>
                  <SignUp onModalClose={this.onModalClose.bind(this)} />
                }
                />
               </Modal>
</View>
```

The modal does not appear. 

However, I have found that by changing isVisible to the regular react-native prop visible and running my app, a normal non animating modal appears. After that, I can change the visibleProp back to the animatedModal prop isVisible, and get an animated modal to appear the first time running the app, but it does not appear on subsequent runs. 

For example, I change isVisible to visible:

```
<Modal
                visible={true}
               >
```

Then run the app. A regular react native modal appears with my views in it. 

After that, I change visible back to isVisible

```
<Modal
                isVisible={true}
               >
```
and run the app again. this time the animated modal appears correctly this one and only run. However if I refresh the app in the simulator, the modal does not appear on subsequent runs. Any ideas how to solve this?

**Comment by mmazzarolo** [comment]
Hey @stonepreston but it's a bit hard for me to debug your issue :)  
Can you try to put the repo [example](https://github.com/mmazzarolo/react-native-animated-modal/tree/master/example/src) in your code and check if it is working correctly for you?  
From my understanding your issue might be related to the fact that you are putting a navigator inside the modal or that your modal is activated on the first render...  
Let me know if the example forks for you (it should, I just tried it locally)

**Comment by stonepreston** [comment]
Yeah it was another piece of code causing some issues. I tried the repo code just by itself and its working fine. Thanks!

**Comment by mmazzarolo** [comment]
No worries man, glad it worked ;)

**Comment by akshaysanthanam** [comment]
The model does not appear for at all, i have tried the code is "A complete example section": 

Code: 
import React, { Component } from "react";
import { Text, TouchableOpacity, View } from "react-native";
import Modal from "react-native-modal";

export default class ModalTester extends Component {
    state = {
        isModalVisible: false
    };

    _toggleModal = () =>
        this.setState({ isModalVisible: !this.state.isModalVisible });

    render() {
        return (
            <View style={{ flex: 1 }}>
                <TouchableOpacity onPress={this._toggleModal}>
                    <Text>Show Modal</Text>
                </TouchableOpacity>
                <Modal isVisible={this.state.isModalVisible}>
                    <View style={{ flex: 1 }}>
                        <Text>Hello!</Text>
                        <TouchableOpacity onPress={this._toggleModal}>
                            <Text>Hide me!</Text>
                        </TouchableOpacity>
                    </View>
                </Modal>
            </View>
        );
    }
}


The modal does not show-up at all.

**Comment by helloeyesimple** [comment]
Does not work for me too like @akshaysanthanam said. IOS environment.

**Comment by liyaolin** [comment]
I also have this question, can not appear by this way,  but  by ternary operator is ok

**Comment by sayo96** [comment]
I'm experiencing the same problem. In my case, modal doesn't appear after a re render but it appears when i reload the app.
@mmazzarolo @akshaysanthanam @helloeyesimple  Do any of you guys have a fix for this problem?
