### ISSUE TITLE
custom component wrapper for Modal

### ISSUE THREAD

**Issue by temitope** [mmazzarolo/react-native-animated-modal#6]
I am trying to create a customized modal for error validation alerts, so I know it is a single button "click to close" pattern of popup and I have styling and can pass in the message and visibility things as props. Instead of creating that each time I wanted to just have a custom modal, but I am not able to do so without errors saying.

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function but got : undefined. You likely forgot to export your component form the file it's defined in. Check the render method of 'ModalValidationCustom'`

also getting 
`ossible Unhandled Promise Rejection (id: 0):
Cannot read property 'transitionTo' of undefined
TypeError: Cannot read property 'transitionTo' of undefined
    at AnimatedModal._callee$`

Sample Code of exponent i am exporting
```
class ModalValidationCustom extends Component{
  constructor(props){
    super(props)
    this.state={
      isVisible:false
    }
    this.handleClose = this.handleClose.bind(this)
  }
  handleClose=()=>{
    if(this.props.handleClose)
      this.props.handleClose()
    else
      console.log("make a handleclose prop function to set state")
  }
  
  render(){
        return(
          <Modal animationIn='zoomIn' animationOut='zoomOut' isVisible={this.props.isVisible || this.state.isVisible}>
            <View style={[styles.center,{ flex: 0,padding:20,borderRadius:10,justifyContent:'space-around', backgroundColor:'#fff' }]}>
              
              <Text style={{marginVertical:15, color:colors.sec_color}}>{this.props.modal_message}</Text>

              <Button 
              title="OK"
              onPress={this.handleClose}
              />
            </View>
        </Modal>
        )
  }
}
```

@mmazzarolo

**Comment by temitope** [comment]
gonna close this for now. i think im making amateur mistakes with importing. will reopen if still an issue.... if you have any comment on the feasibility lemme know

**Comment by mmazzarolo** [comment]
> if you have any comment on the feasibility (like should this be possible even?) appreciated  

Yes, it is possible.  
I would highly recommend to change this: 
```javascript
isVisible={this.props.isVisible || this.state.isVisible}>
```  

to this:
```javascript
isVisible={this.props.isVisible}>
```  

And to handle the visibility state of the modal externally.

**Comment by temitope** [comment]
@mmazzarolo thank you.
