### ISSUE TITLE
Is it possible to set animatable V1.1.1 in dependencies?

### ISSUE THREAD

**Issue by Nyl000** [mmazzarolo/react-native-animated-modal#9]
Hi,
First, thanks you for this awesome module ! 
This module uses animatable 0.6.1 as dependency. 

Is it possible to switch to 1.1.1 ? 
It permit to define custom animations via Animatable.initializeRegistryWithDefinitions :)

Thx !

**Comment by mmazzarolo** [comment]
Hey @Nyl000, of course!  Would you mind sending a PR? 
Otherwise I'll update it by myself when I have some spare time!

**Comment by Nyl000** [comment]
Sure :) , done here : https://github.com/mmazzarolo/react-native-animated-modal/pull/10
Thanks !
